language: node_js
node_js: node
cache:
  directories:
  - node_modules
env:
- CI=true
deploy:
  provider: heroku:git
  api_key:
    secure: pCcuJB6nc3ljpyVrNMkUdgxCuqYyTK5SVy0v6KvRoTJ7x0p+DmocD2pRo/RIZK3E93b7jus+yDCwFR1pDYU+jweWk6SokSdAabgydoHnspp8xO8KJw81pN4L++geFTdYItqOE7Z7mwNeVshpzPAv4KJk8dI4oQHLb5uT9/V8+3tWPR/Zpk5gYLev2ZbD0MEDPKDGiZ+nHDoA3QBfz6Vx2NL94xX7J6dL9FFFkNTRK6Xhm3lria/j1agA75y/FQqDCBqXSE6KrPo+5R9KnkOtbpjb6CU0nqXFeyjTtf78uldqxHKD3qxvklGkKm/qLkRabOM3V2Rl6S1JriRCPDJbXFrcSz7v97l8rWuqRCQ+k2pGIlE+DCWYFt3wNvjusbnFaoUVFz05gxBXFrGDvbHqYzHYA9sS/xsQoIh7G8VejZjHBWSIffA6eHgB7jrnqmNIRRmgsMiOREizXOAd3ZRO5MdfYhHVjZcwgQegDuPaK9UN5yPchlrNQuUzBLWIIDAcMDf2BSuyuSkaNRG8pNS3Qx76pskViRgWr2vIEMXbDGnKYsv/omnadKV+axOV93yfa8XrjG7/161LFfsNpBx9UUy+9E+qPnbprMuMWzCXcsMU1MfWP6JBAE+HGHzrVn76WkSLd6H70bhzAHBEM9DCyy9qO5z/MZIqQ/FYUEBUtXI=
